import contextlib
import os
import subprocess
from pathlib import Path
from typing import Optional

from apatchy.compat import extract_version_from_path, get_compat_flags
from apatchy.core import toolchain_config
from apatchy.core.harness import HarnessBuilder
from apatchy.core.process_runner import ProcessRunner
from apatchy.managers.config_manager import ConfigManager
from apatchy.utils.logger import get_logger

logger = get_logger(__name__)


def _bear_available() -> bool:
    """Check if the ``bear`` CLI tool is installed."""
    return toolchain_config.resolve_tool("bear") is not None


class BuildManager:
    """High-level build orchestration for Apache HTTPD and fuzzing harnesses.

    ``BuildManager`` drives the three main build steps: ``configure``,
    ``make``, and ``link``. It delegates flag generation to
    :class:`~apatchy.managers.config_manager.ConfigManager` and harness
    compilation to :class:`~apatchy.core.harness.HarnessBuilder`, adding
    dependency detection (PCRE, Expat), version-specific compat flags, and
    optional ``bear`` integration for ``compile_commands.json`` generation.

    The configure step (:meth:`configure_httpd`) runs Apache's
    ``./configure`` with a static-only, all-modules build. It automatically
    detects PCRE and Expat locations, enables APR pool debug mode when ASan
    is active (so ASan can track individual pool allocations), and appends
    any version-specific flags from the :mod:`apatchy.compat` registry.

    The compile step (:meth:`compile_httpd`) runs ``make`` with parallel
    jobs (defaults to CPU count). When ``bear=True``, it wraps the build
    with ``bear`` to produce a ``compile_commands.json`` and updates
    the ``.clangd`` config for IDE integration.

    The link step (:meth:`build_harness`) compiles and links the fuzzing
    harness against the Apache build tree:

    * ``"libfuzzer"`` - compiled with ``clang`` and ``-fsanitize=fuzzer``.

    A coverage-instrumented harness (``fuzz_harness_coverage``) is built
    separately by :class:`~apatchy.managers.report_manager.ReportManager`
    for triage and coverage reports.

    Args:
        httpd_root: Path to the Apache HTTPD source directory
            (e.g. ``httpd-2.4.58/``).
        config_manager: A :class:`~apatchy.managers.config_manager.ConfigManager`
            instance that provides the compiler flags and sanitizer settings.
        verbose: Show full build output instead of a progress spinner.

    CLI usage:

    .. code-block:: bash

        # Configure Apache for fuzzing with ASan
        apatchy configure --mode fuzz --asan

        # Compile with bear for IDE support
        apatchy compile --bear

        # Link the harness
        apatchy link --engine libfuzzer

    Example:
        .. code-block:: python

            from pathlib import Path
            from apatchy.managers.config_manager import ConfigManager
            from apatchy.managers.build_manager import BuildManager

            config = ConfigManager(build_mode="fuzz", asan=True)
            bm = BuildManager(Path("httpd-2.4.58"), config)

            bm.configure_httpd()
            bm.compile_httpd(bear=True)
            bm.build_harness(mode="libfuzzer")
    """

    def __init__(self, httpd_root: Path, config_manager: ConfigManager, verbose: bool = False) -> None:
        self.httpd_root = httpd_root
        self.config_manager = config_manager
        self.verbose = verbose
        self.logger = logger
        self.runner = ProcessRunner(verbose=verbose)
        self.harness_builder = HarnessBuilder(httpd_root, verbose=verbose)

    def _update_clangd(self) -> None:
        """Write a ``.clangd`` file at the project root with compilation database entries.

        Creates entries for both the harness sources and the httpd sources,
        using the actual httpd directory name to handle varying Apache versions.
        """
        from apatchy.config import Config

        project_root = Config.PROJECT_ROOT
        httpd_rel = self.httpd_root.relative_to(project_root)
        harnesses_rel = Config.HARNESSES_DIR.relative_to(project_root)

        content = (
            f"# .clangd - auto-generated by apatchy --bear\n"
            f"If:\n"
            f"  PathMatch: {harnesses_rel}/.*\n"
            f"CompileFlags:\n"
            f"  CompilationDatabase: {harnesses_rel}/\n"
            f"\n"
            f"---\n"
            f"If:\n"
            f"  PathMatch: {httpd_rel}/.*\n"
            f"CompileFlags:\n"
            f"  CompilationDatabase: {httpd_rel}/\n"
        )

        clangd_path = project_root / ".clangd"
        clangd_path.write_text(content)
        self.logger.info(f"Updated {clangd_path}")

    def configure_httpd(self, extra_flags: Optional[list] = None) -> None:
        """Run ``./configure`` with optimised flags."""
        httpd_version = extract_version_from_path(self.httpd_root)
        config = self.config_manager.generate_build_config(httpd_version=httpd_version)
        cflags = config["CFLAGS"]
        ldflags = config["LDFLAGS"]

        self.logger.info(f"Configuring Apache in {self.httpd_root}")
        self.logger.info(f"CFLAGS: {cflags}")

        # Detect PCRE
        pcre_prefix = None
        pcre_config = toolchain_config.resolve_tool("pcre-config") or toolchain_config.resolve_tool("pcre2-config")

        if pcre_config:
            with contextlib.suppress(subprocess.CalledProcessError):
                # We use subprocess directly here to avoid logging noise
                pcre_prefix = subprocess.check_output([pcre_config, "--prefix"], text=True).strip()

        configure_cmd = [
            "./configure",
            "--with-included-apr",
            "--disable-shared",  # Static-only APR/APR-Util (no .so at runtime)
            "--disable-util-dso",  # Static-link crypto/dbd/dbm drivers into libaprutil
            "--enable-mods-static=all",
            "--enable-maintainer-mode",
            "--enable-debugger-mode",
            "--disable-pie",
            # mod_session_crypto requires APR-Util crypto support (OpenSSL)
            "--with-crypto",
            "--enable-session",
            "--enable-session-cookie",
            "--enable-session-crypto",
        ]

        # When ASan is enabled, make apr_palloc() use direct malloc()
        # so ASan can track individual pool allocations.
        if self.config_manager.asan:
            self.logger.info("Enabling APR pool debug mode for ASan")
            configure_cmd.append("--enable-pool-debug=yes")

        if pcre_prefix:
            self.logger.info(f"Using PCRE prefix: {pcre_prefix}")
            configure_cmd.append(f"--with-pcre={pcre_prefix}")
        else:
            self.logger.warning("pcre-config not found. Configure might fail if PCRE is not in standard paths.")

        # Detect Expat
        expat_prefix = None
        bundled_expat = self.httpd_root / "srclib" / "apr-util" / "xml" / "expat"

        if bundled_expat.exists():
            self.logger.info(f"Using bundled Expat in {bundled_expat}")
            # apr-util automatically uses bundled expat if present in xml/expat
        else:
            if toolchain_config.resolve_tool("pkg-config"):
                with contextlib.suppress(subprocess.CalledProcessError):
                    # We use subprocess directly here to avoid logging noise
                    expat_prefix = subprocess.check_output(
                        ["pkg-config", "--variable=prefix", "expat"], text=True
                    ).strip()

            if not expat_prefix:
                if Path("/usr/include/expat.h").exists():
                    expat_prefix = "/usr"
                elif Path("/usr/local/include/expat.h").exists():
                    expat_prefix = "/usr/local"

            if expat_prefix:
                self.logger.info(f"Using Expat prefix: {expat_prefix}")
                configure_cmd.append(f"--with-expat={expat_prefix}")
            else:
                self.logger.warning("Expat not found. apr-util configure might fail.")

        # Apply version-specific configure arguments from the compat
        # registry (e.g. extra --with-* or --disable-* flags).
        if httpd_version:
            compat = get_compat_flags(httpd_version)
            for arg in compat.configure_args:
                self.logger.info(f"Adding compat configure arg: {arg}")
            configure_cmd.extend(compat.configure_args)

        cc = config.get("CC")
        if cc:
            self.logger.info(f"Using CC: {cc}")
            configure_cmd.append(f"CC={cc}")

        if extra_flags:
            configure_cmd.extend(extra_flags)

        configure_cmd.extend([f"CFLAGS={cflags}", f"LDFLAGS={ldflags}"])

        self.runner.run_build(configure_cmd, label="Configuring Apache", cwd=self.httpd_root)

        # Save build metadata so branches can inherit sanitizer state
        from apatchy.core.build_meta import BuildMeta
        from apatchy.utils.build_tree import AlternateBuildTree

        meta = BuildMeta(
            tree="vanilla",
            cc=cc or "clang",
            cflags=cflags,
            ldflags=ldflags,
            asan=self.config_manager.asan,
            ubsan=self.config_manager.ubsan,
            ubsan_ignorelist=self.config_manager.ubsan_ignorelist,
            intsan=self.config_manager.intsan,
            truncsan=self.config_manager.truncsan,
            httpd_version=httpd_version or "",
            config_hash=AlternateBuildTree.config_hash(self.httpd_root),
        )
        meta.save(self.httpd_root)
        self.logger.info(f"Saved build metadata to {self.httpd_root.name}/.apatchy_build.json")

    def compile_httpd(self, jobs: int = None, clean: bool = True, bear: bool = False) -> None:
        """Compile Apache HTTPD with ``make``, optionally wrapped by ``bear``."""
        if jobs is None:
            jobs = os.cpu_count() or 1
        if clean:
            self.logger.info("Cleaning previous build...")
            self.runner.run_build(["make", "clean"], label="Cleaning build", cwd=self.httpd_root)

        if bear:
            if not _bear_available():
                self.logger.error("bear not found in PATH. Install it: apt install bear")
                raise FileNotFoundError("bear not found in PATH")
            self.logger.info(f"Compiling Apache with {jobs} jobs (bear enabled)...")
            self.runner.run_build(
                ["bear", "--", "make", f"-j{jobs}"],
                label="Compiling Apache",
                cwd=self.httpd_root,
            )
            self._update_clangd()
        else:
            self.logger.info(f"Compiling Apache with {jobs} jobs...")
            self.runner.run_build(["make", f"-j{jobs}"], label="Compiling Apache", cwd=self.httpd_root)

    def build_harness(
        self,
        mode: str = "libfuzzer",
        harness_name: str = None,
        bear: bool = False,
        cflags: str = "",
        ldflags: str = "",
    ) -> None:
        """Build the fuzzing harness for the given engine.

        The caller is responsible for pointing ``httpd_root`` at the
        correct build tree (e.g. the ``-lf`` branch for libfuzzer).
        """
        self.logger.info(f"Building harness for engine: {mode}")

        if bear and not _bear_available():
            self.logger.error("bear not found in PATH. Install it: apt install bear")
            raise FileNotFoundError("bear not found in PATH")

        self.harness_builder.build(
            mode=mode,
            cflags=cflags,
            ldflags=ldflags,
            harness_name=harness_name,
            bear=bear,
        )

        if bear:
            self._update_clangd()
