"""High-level build orchestration for Apache HTTPD and fuzzing harnesses.

:class:`BuildManager` ties together :class:`~apatchy.managers.config_manager.ConfigManager`
(compiler/flag selection) and :class:`~apatchy.core.harness.HarnessBuilder`
(harness compilation) behind the ``configure``, ``compile``, and ``build``
CLI commands.
"""

import os
import shutil
import subprocess
from pathlib import Path

from apatchy.compat import extract_version_from_path, get_compat_flags
from apatchy.core.harness import HarnessBuilder
from apatchy.core.process_runner import ProcessRunner
from apatchy.managers.config_manager import ConfigManager
from apatchy.utils.logger import get_logger

logger = get_logger(__name__)


def _bear_available() -> bool:
    """Check if the ``bear`` CLI tool is installed."""
    return shutil.which("bear") is not None


class BuildManager:
    """Orchestrate Apache ``./configure``, ``make``, and harness builds."""

    def __init__(self, httpd_root: Path, config_manager: ConfigManager, verbose: bool = False) -> None:
        self.httpd_root = httpd_root
        self.config_manager = config_manager
        self.verbose = verbose
        self.logger = logger
        self.runner = ProcessRunner(verbose=verbose)
        self.harness_builder = HarnessBuilder(httpd_root, verbose=verbose)

    def _update_clangd(self) -> None:
        """Write a ``.clangd`` file at the project root with compilation database entries.

        Creates entries for both the harness sources and the httpd sources,
        using the actual httpd directory name to handle varying Apache versions.
        """
        from apatchy.config import Config

        project_root = Config.PROJECT_ROOT
        httpd_rel = self.httpd_root.relative_to(project_root)
        harnesses_rel = Config.HARNESSES_DIR.relative_to(project_root)

        content = (
            f"# .clangd - auto-generated by apatchy --bear\n"
            f"If:\n"
            f"  PathMatch: {harnesses_rel}/.*\n"
            f"CompileFlags:\n"
            f"  CompilationDatabase: {harnesses_rel}/\n"
            f"\n"
            f"---\n"
            f"If:\n"
            f"  PathMatch: {httpd_rel}/.*\n"
            f"CompileFlags:\n"
            f"  CompilationDatabase: {httpd_rel}/\n"
        )

        clangd_path = project_root / ".clangd"
        clangd_path.write_text(content)
        self.logger.info(f"Updated {clangd_path}")

    def configure_httpd(self) -> None:
        """
        Runs ./configure with optimised flags.
        """
        httpd_version = extract_version_from_path(self.httpd_root)
        config = self.config_manager.generate_build_config(httpd_version=httpd_version)
        cflags = config["CFLAGS"]
        ldflags = config["LDFLAGS"]

        self.logger.info(f"Configuring Apache in {self.httpd_root}")
        self.logger.info(f"CFLAGS: {cflags}")

        # Detect PCRE
        pcre_prefix = None
        pcre_config = shutil.which("pcre-config") or shutil.which("pcre2-config")

        if pcre_config:
            try:
                # We use subprocess directly here to avoid logging noise
                pcre_prefix = subprocess.check_output([pcre_config, "--prefix"], text=True).strip()
            except subprocess.CalledProcessError:
                pass

        configure_cmd = [
            "./configure",
            "--with-included-apr",
            "--disable-shared",  # Static-only APR/APR-Util (no .so at runtime)
            "--disable-util-dso",  # Static-link crypto/dbd/dbm drivers into libaprutil
            "--enable-mods-static=all",
            "--enable-maintainer-mode",
            "--enable-debugger-mode",
            "--disable-pie",
            # mod_session_crypto requires APR-Util crypto support (OpenSSL)
            "--with-crypto",
            "--enable-session",
            "--enable-session-cookie",
            "--enable-session-crypto",
        ]

        # When ASan is enabled, make apr_palloc() use direct malloc()
        # so ASan can track individual pool allocations.
        if self.config_manager.asan:
            self.logger.info("Enabling APR pool debug mode for ASan")
            configure_cmd.append("--enable-pool-debug=yes")

        if pcre_prefix:
            self.logger.info(f"Using PCRE prefix: {pcre_prefix}")
            configure_cmd.append(f"--with-pcre={pcre_prefix}")
        else:
            self.logger.warning("pcre-config not found. Configure might fail if PCRE is not in standard paths.")

        # Detect Expat
        expat_prefix = None
        bundled_expat = self.httpd_root / "srclib" / "apr-util" / "xml" / "expat"

        if bundled_expat.exists():
            self.logger.info(f"Using bundled Expat in {bundled_expat}")
            # apr-util automatically uses bundled expat if present in xml/expat
        else:
            if shutil.which("pkg-config"):
                try:
                    # We use subprocess directly here to avoid logging noise
                    expat_prefix = subprocess.check_output(
                        ["pkg-config", "--variable=prefix", "expat"], text=True
                    ).strip()
                except subprocess.CalledProcessError:
                    pass

            if not expat_prefix:
                if Path("/usr/include/expat.h").exists():
                    expat_prefix = "/usr"
                elif Path("/usr/local/include/expat.h").exists():
                    expat_prefix = "/usr/local"

            if expat_prefix:
                self.logger.info(f"Using Expat prefix: {expat_prefix}")
                configure_cmd.append(f"--with-expat={expat_prefix}")
            else:
                self.logger.warning("Expat not found. apr-util configure might fail.")

        # Apply version-specific configure arguments from the compat
        # registry (e.g. extra --with-* or --disable-* flags).
        if httpd_version:
            compat = get_compat_flags(httpd_version)
            for arg in compat.configure_args:
                self.logger.info(f"Adding compat configure arg: {arg}")
            configure_cmd.extend(compat.configure_args)

        cc = config.get("CC")
        if cc:
            self.logger.info(f"Using CC: {cc}")
            configure_cmd.append(f"CC={cc}")

        configure_cmd.extend([f"CFLAGS={cflags}", f"LDFLAGS={ldflags}"])

        self.runner.run_build(configure_cmd, label="Configuring Apache", cwd=self.httpd_root)

    def compile_httpd(self, jobs: int = None, clean: bool = True, bear: bool = False) -> None:
        if jobs is None:
            jobs = os.cpu_count() or 1
        if clean:
            self.logger.info("Cleaning previous build...")
            self.runner.run_build(["make", "clean"], label="Cleaning build", cwd=self.httpd_root)

        if bear:
            if not _bear_available():
                self.logger.error("bear not found in PATH. Install it: apt install bear")
                raise FileNotFoundError("bear not found in PATH")
            self.logger.info(f"Compiling Apache with {jobs} jobs (bear enabled)...")
            self.runner.run_build(
                ["bear", "--", "make", f"-j{jobs}"],
                label="Compiling Apache",
                cwd=self.httpd_root,
            )
            self._update_clangd()
        else:
            self.logger.info(f"Compiling Apache with {jobs} jobs...")
            self.runner.run_build(["make", f"-j{jobs}"], label="Compiling Apache", cwd=self.httpd_root)

    def build_harness(
        self, mode: str = "standalone", engine: str = "standalone", harness_name: str = None, bear: bool = False
    ) -> None:
        self.logger.info(f"Building harness for engine: {mode}")

        if bear and not _bear_available():
            self.logger.error("bear not found in PATH. Install it: apt install bear")
            raise FileNotFoundError("bear not found in PATH")

        # Get flags from config manager again to ensure consistency
        # (e.g. if we are building ASan harness, we need ASan flags)
        # Note: 'mode' arg here comes from CLI (e.g. 'afl', 'libfuzzer')
        # 'engine' arg is redundancy, can clean up

        httpd_version = extract_version_from_path(self.httpd_root)
        config = self.config_manager.generate_build_config(httpd_version=httpd_version)
        cflags = config["CFLAGS"]
        ldflags = config["LDFLAGS"]

        # Standalone harness is compiled with plain clang (no AFL defines)
        # but links against the existing Apache build tree. This avoids
        # the expensive separate tree rebuild while still producing a
        # binary that reads from stdin (for crash triage).
        if mode == "standalone":
            self.harness_builder.build(
                mode=mode, cflags=cflags, ldflags=ldflags, harness_name=harness_name, cc="clang", bear=bear
            )
        else:
            self.harness_builder.build(mode=mode, cflags=cflags, ldflags=ldflags, harness_name=harness_name, bear=bear)

        if bear:
            self._update_clangd()
