# CVE-2021-44790
ServerName localhost:80

RequestReadTimeout handshake=0 header=0 body=0
DocumentRoot "/tmp/htdocs"
ErrorLog "/dev/stderr"
LogLevel emerg

<Directory "/">
    Require all granted
</Directory>

<Files "*.lua">
    SetHandler lua-script
</Files>
