http_req {
  method: GET
  uri: "/a"
  headers { name: "Host" value: "localhost" }
}
coord_x: "110"
coord_y: "110"
map_directive_key: DIRECTIVE_CIRCLE
map_directive_value: "http://example.com/ 100,100 200,200"
