http_req {
  method: GET
  uri: "/c"
  headers { name: "Host" value: "localhost" }
}
coord_x: "155"
coord_y: "100"
map_directive_key: DIRECTIVE_DEFAULT
map_directive_value: "test://circle.com/ 100,100"
