# CVE-2021-26690
ServerName localhost:8080

Timeout 5
KeepAlive Off

DocumentRoot "/tmp/htdocs"
ErrorLog /dev/null
LogLevel emerg

TypesConfig /dev/null

SessionCryptoDriver openssl

<Directory "/tmp/htdocs">
    Require all granted
</Directory>

<Directory />
    Require all denied
</Directory>

<Location "/k">
    Session On
    SessionEnv On
    SessionCookieName session_strip path=/
    SessionCookieRemove On
    SessionMaxAge 300
</Location>
