"""Tests for apatchy.core.toolchain_config INI handling.

Uses tmp_path for real file I/O - no mocking.
"""

import configparser
from unittest.mock import patch

from apatchy.core import toolchain_config


@patch.object(toolchain_config, "_config_path")
def test_load_creates_sections(mock_path, tmp_path):
    """load() creates all expected sections."""
    mock_path.return_value = tmp_path / "toolchain.config"
    cp = toolchain_config.load()
    for section in toolchain_config.SECTIONS:
        assert cp.has_section(section)


@patch.object(toolchain_config, "_config_path")
def test_load_missing_file(mock_path, tmp_path):
    """load() handles missing file gracefully."""
    mock_path.return_value = tmp_path / "nonexistent.config"
    cp = toolchain_config.load()
    assert isinstance(cp, configparser.ConfigParser)
    for section in toolchain_config.SECTIONS:
        assert cp.has_section(section)


@patch.object(toolchain_config, "_config_path")
def test_save_and_load_roundtrip(mock_path, tmp_path):
    """save() then load() preserves data."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    cp = toolchain_config.load()
    cp.set("build", "cc", "/usr/bin/clang")
    cp.set("fuzzing", "afl-fuzz", "/usr/bin/afl-fuzz")
    toolchain_config.save(cp)

    cp2 = toolchain_config.load()
    assert cp2.get("build", "cc") == "/usr/bin/clang"
    assert cp2.get("fuzzing", "afl-fuzz") == "/usr/bin/afl-fuzz"


@patch.object(toolchain_config, "_config_path")
def test_save_writes_header(mock_path, tmp_path):
    """save() writes the auto-generated header comment."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    cp = toolchain_config.load()
    toolchain_config.save(cp)

    content = config_file.read_text()
    assert "Auto-generated by: apatchy setup" in content


@patch.object(toolchain_config, "_config_path")
def test_resolve_tool_from_config(mock_path, tmp_path):
    """resolve_tool() returns path stored in config."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    fake_tool = tmp_path / "my-clang"
    fake_tool.touch()

    cp = toolchain_config.load()
    cp.set("build", "cc", str(fake_tool))
    toolchain_config.save(cp)

    result = toolchain_config.resolve_tool("cc", section="build")
    assert result == str(fake_tool)


@patch.object(toolchain_config, "_config_path")
def test_resolve_tool_falls_back_to_path(mock_path, tmp_path):
    """resolve_tool() falls back to shutil.which() on PATH."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    result = toolchain_config.resolve_tool("python3")
    assert result is not None
    assert "python3" in result


@patch.object(toolchain_config, "_config_path")
def test_resolve_tool_not_found(mock_path, tmp_path):
    """resolve_tool() returns None for nonexistent tool."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    result = toolchain_config.resolve_tool("nonexistent_tool_xyz_99999")
    assert result is None


@patch.object(toolchain_config, "_config_path")
def test_resolve_tool_invalid_path_in_config(mock_path, tmp_path):
    """Stale config path falls back to PATH lookup."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    cp = toolchain_config.load()
    cp.set("build", "cc", "/nonexistent/path/clang")
    toolchain_config.save(cp)

    result = toolchain_config.resolve_tool("cc", section="build")
    assert result != "/nonexistent/path/clang"


@patch.object(toolchain_config, "_config_path")
def test_update_section_merges(mock_path, tmp_path):
    """update_section() preserves existing valid entries."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    tool_a = tmp_path / "tool_a"
    tool_a.touch()
    tool_b = tmp_path / "tool_b"
    tool_b.touch()
    tool_c = tmp_path / "tool_c"
    tool_c.touch()

    cp = toolchain_config.load()
    cp.set("build", "cc", str(tool_a))
    toolchain_config.save(cp)

    toolchain_config.update_section(
        "build",
        {
            "cc": str(tool_b),
            "ld": str(tool_c),
        },
    )

    cp2 = toolchain_config.load()
    assert cp2.get("build", "cc") == str(tool_a)  # preserved
    assert cp2.get("build", "ld") == str(tool_c)  # added


@patch.object(toolchain_config, "_config_path")
def test_force_update_section_overwrites(mock_path, tmp_path):
    """force_update_section() overwrites existing entries."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    tool_a = tmp_path / "tool_a"
    tool_a.touch()
    tool_b = tmp_path / "tool_b"
    tool_b.touch()

    cp = toolchain_config.load()
    cp.set("build", "cc", str(tool_a))
    toolchain_config.save(cp)

    toolchain_config.force_update_section(
        "build",
        {
            "cc": str(tool_b),
        },
    )

    cp2 = toolchain_config.load()
    assert cp2.get("build", "cc") == str(tool_b)  # overwritten


@patch.object(toolchain_config, "_config_path")
def test_update_section_creates_section(mock_path, tmp_path):
    """update_section() creates a new section if needed."""
    config_file = tmp_path / "toolchain.config"
    mock_path.return_value = config_file

    toolchain_config.update_section("custom", {"key": "value"})

    cp = toolchain_config.load()
    assert cp.has_section("custom")
    assert cp.get("custom", "key") == "value"
