"""Persistent toolchain configuration via INI file.

Stores discovered tool paths in WORK_DIR/toolchain.config so that
setup commands (check, afl, llvm) don't require manual PATH exports.
Human-editable: clear a value to force re-detection, set a value to
override auto-detection.
"""

import configparser
import shutil
from pathlib import Path
from typing import Dict, Optional

from apatchy.config import Config

SECTIONS = ("build", "fuzzing", "coverage", "libraries")

HEADER_COMMENT = (
    "# Auto-generated by: apatchy setup\n"
    "# Manual edits are preserved. Clear a value to force re-detection.\n\n"
)


def _config_path() -> Path:
    return Config.TOOLCHAIN_CONFIG


def load() -> configparser.ConfigParser:
    """Read the config file, ensuring all expected sections exist."""
    cp = configparser.ConfigParser()
    cp.read(str(_config_path()))
    for section in SECTIONS:
        if not cp.has_section(section):
            cp.add_section(section)
    return cp


def save(cp: configparser.ConfigParser) -> None:
    """Write config back to disk with a header comment."""
    path = _config_path()
    with open(path, "w") as f:
        f.write(HEADER_COMMENT)
        cp.write(f)


def resolve_tool(name: str, section: Optional[str] = None) -> Optional[str]:
    """Look up a tool path: config first (validate on disk), then shutil.which().

    If *section* is given, only that section is checked. Otherwise all
    sections are scanned for a matching key.
    """
    cp = load()
    sections = [section] if section else list(SECTIONS)

    for sec in sections:
        if not cp.has_section(sec):
            continue
        value = cp.get(sec, name, fallback=None)
        if value and _path_valid(value):
            return value

    # Fallback to PATH lookup
    found = shutil.which(name)
    return found


def update_section(section: str, entries: Dict[str, str]) -> None:
    """Merge entries into a section, preserving existing non-empty values (user overrides)."""
    cp = load()
    if not cp.has_section(section):
        cp.add_section(section)
    for key, value in entries.items():
        existing = cp.get(section, key, fallback=None)
        if existing and existing.strip() and _path_valid(existing):
            continue  # preserve user override / still-valid path
        cp.set(section, key, value)
    save(cp)


def force_update_section(section: str, entries: Dict[str, str]) -> None:
    """Unconditionally overwrite entries in a section (e.g. after building tools)."""
    cp = load()
    if not cp.has_section(section):
        cp.add_section(section)
    for key, value in entries.items():
        cp.set(section, key, value)
    save(cp)


def get_tool_path(name: str) -> Optional[str]:
    """Convenience alias - resolve a tool path from config or PATH."""
    return resolve_tool(name)


def _path_valid(value: str) -> bool:
    """Check if a config value points to something that exists.

    Handles both plain paths and pkg-config: style entries.
    """
    if value.startswith("pkg-config:"):
        return bool(shutil.which("pkg-config"))
    return Path(value).exists()
