# configs/fuzz.conf - Default minimal httpd config for fuzzing
ServerName localhost:80
HttpProtocolOptions Unsafe
RequestReadTimeout handshake=0 header=0 body=0
DocumentRoot "/tmp/htdocs"
ErrorLog "/dev/stderr"
LogLevel emerg

<Directory "/">
    Require all granted
</Directory>
