# Listen 8088
# Setup requirements:
#   mkdir -p /tmp/htdocs/
#   cp framework/configs/test.map /tmp/htdocs/test.map

ServerRoot "/tmp"
DefaultRuntimeDir "/tmp"
PidFile "/tmp/httpd.pid"
TypesConfig conf/mime.types
ServerName localhost:80
HttpProtocolOptions Unsafe
RequestReadTimeout handshake=0 header=0 body=0
DocumentRoot "/tmp/htdocs"
ErrorLog "/dev/stderr"
# ErrorLog "/tmp/error.log"
LogLevel emerg

<Directory "/tmp/htdocs">
    AllowOverride All
    Require all granted
    AddHandler imap-file map
    ImapMenu formatted
</Directory>

Alias "/a" "/tmp/htdocs/test.map"
Alias "/b" "/tmp/htdocs/test.map"
Alias "/c" "/tmp/htdocs/test.map"

<Location "/a">
    SetHandler imap-file
    ImapMenu semiformatted
</Location>

<Location "/b">
    SetHandler imap-file
    ImapMenu unformatted
</Location>

<Location "/c">
    SetHandler imap-file
    ImapMenu none
</Location>

