# Listen 8080
# Setup requirements:
#   mkdir -p /tmp/htdocs/
#   cp framework/configs/test.map /tmp/htdocs/test.map

ServerName localhost:80
HttpProtocolOptions Unsafe
RequestReadTimeout handshake=0 header=0 body=0
DocumentRoot "/tmp/htdocs"
ErrorLog "/dev/stderr"
LogLevel emerg

<Directory "/tmp/htdocs">
    AllowOverride All
    Require all granted
    AddHandler imap-file map
    # ImapMenu semiformatted
</Directory>