# configs/remotip.conf - mod_remoteip fuzzing config
ServerName localhost:80
HttpProtocolOptions Unsafe
DocumentRoot "/tmp/htdocs"
ErrorLog "/dev/stderr"
# LogLevel debug

RemoteIPProxyProtocol On

LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

<Directory "/">
    Require all granted
</Directory>
