# configs/uwsgi.conf
ServerName localhost:80
Timeout 2
ProxyTimeout 2
HttpProtocolOptions Unsafe
DocumentRoot "/tmp/htdocs"
ErrorLog "/dev/null"
LogLevel emerg 
TypesConfig conf/mime.types

<Directory "/">
    Require all granted
</Directory>

ProxyRequests Off
ProxyErrorOverride On
ProxyPass "/a" "uwsgi://127.0.0.1:3032/" nocanon
ProxyPass "/" "uwsgi://127.0.0.1:3032/"
ProxyPassReverse "/" "uwsgi://127.0.0.1:3032/"

LimitRequestFieldSize 100000 
LimitRequestLine 100000