# configs/uwsgi.conf
ServerName localhost:80
Timeout 2
ProxyTimeout 2
HttpProtocolOptions Unsafe
DocumentRoot "/tmp/htdocs"
ErrorLog "/dev/stdout"
LogLevel emerg
TypesConfig conf/mime.types

<Directory "/">
    Require all granted
</Directory>

ProxyRequests Off
ProxyErrorOverride On

# nocanon path (lines 88-89)
ProxyPass "/a" "uwsgi://127.0.0.1:3032/" nocanon

# # non-uwsgi scheme, triggers DECLINED in uwsgi_canon/uwsgi_handler (lines 67, 512)
<Location "/b">
    ProxyPass "woot://127.0.0.1:3032/"
</Location>

<Location "/e">
    ProxyPass "http://127.0.0.1:3032/"
</Location>

# IPv6 literal host (lines 83-85)
ProxyPass "/c" "uwsgi://[::1]:3032/"

# default port 3031, triggers sport[0]='\0' (lines 80-81)
ProxyPass "/d" "uwsgi://127.0.0.1/"

# regular canon path
ProxyPass "/" "uwsgi://127.0.0.1:3032/"
ProxyPassReverse "/" "uwsgi://127.0.0.1:3032/"

LimitRequestFieldSize 100000 
LimitRequestLine 100000

# DumpIOInput On
# DumpIOOutput On
# LogLevel dumpio:trace7