# configs/dav.conf
ServerName localhost:80
HttpProtocolOptions Unsafe
RequestReadTimeout handshake=0 header=0 body=0
DocumentRoot "/tmp/htdocs"
ErrorLog "/tmp/fuzz_error.log"
TypesConfig conf/mime.types

# DAV lock database
DavLockDB "/tmp/DavLock"

<Directory "/tmp/htdocs/dav">
    Dav On
    Require all granted
</Directory>
